# Generated by Django 3.0.11 on 2021-05-31 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
