# Generated by Django 3.0.11 on 2021-05-30 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='products.Color', verbose_name='Color'),
            preserve_default=False,
        ),
    ]
