# Generated by Django 3.0.11 on 2021-05-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='video',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='video_url',
            field=models.URLField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
